# Generated by Air env. Do not edit this file directly.
# shellcheck shell=bash

if [ -r "${AIR_STATE_HOME:-$HOME/.local/share/air/state}/plugins/env/enabled" ]; then
    _air_env_prepend_path() {
        case ":${PATH:-}:" in
            *":$1:"*) ;;
            *) PATH="$1${PATH:+:$PATH}" ;;
        esac
    }
    _air_env_expand_path_var() {
        REPLY="$1"
        case "$REPLY" in
            '~') REPLY="$HOME" ;;
            '~/'*) REPLY="$HOME/${REPLY#~/}" ;;
            '$HOME') REPLY="$HOME" ;;
            '$HOME/'*) REPLY="$HOME/${REPLY#\$HOME/}" ;;
        esac
    }

# capability: local-bin (bashrc)
AIR_ENV_PARAM_LOCAL_BIN_BIN_DIR='$HOME/.local/bin'
_air_env_expand_path_var "${AIR_ENV_PARAM_LOCAL_BIN_BIN_DIR:-$HOME/.local/bin}"
_air_env_local_bin_dir="$REPLY"
if [ -d "$_air_env_local_bin_dir" ]; then
    _air_env_prepend_path "$_air_env_local_bin_dir"
    export PATH
fi
unset _air_env_local_bin_dir

# capability: pyenv (bashrc)
AIR_ENV_PARAM_PYENV_PYENV_ROOT='$HOME/.pyenv'
_air_env_expand_path_var "${AIR_ENV_PARAM_PYENV_PYENV_ROOT:-$HOME/.pyenv}"
export PYENV_ROOT="${PYENV_ROOT:-$REPLY}"
if [ -d "$PYENV_ROOT/shims" ]; then
    _air_env_prepend_path "$PYENV_ROOT/shims"
fi
if [ -d "$PYENV_ROOT/bin" ]; then
    _air_env_prepend_path "$PYENV_ROOT/bin"
fi
export PYENV_ROOT PATH

_air_env_pyenv_load() {
    unset -f pyenv 2>/dev/null || true
    command -v pyenv >/dev/null 2>&1 || return 127
    eval "$(command pyenv init --path)"
    eval "$(command pyenv init -)"
}

pyenv() {
    _air_env_pyenv_load || return "$?"
    pyenv "$@"
}

# capability: nvm (bashrc)
AIR_ENV_PARAM_NVM_NVM_DIR='$HOME/.nvm'
AIR_ENV_PARAM_NVM_NODE_VERSION='default'
_air_env_expand_path_var "${AIR_ENV_PARAM_NVM_NVM_DIR:-$HOME/.nvm}"
export NVM_DIR="${NVM_DIR:-$REPLY}"
_air_env_nvm_version="${AIR_ENV_PARAM_NVM_NODE_VERSION:-default}"
if [ -n "${NVM_BIN:-}" ] && [ -d "$NVM_BIN" ]; then
    _air_env_prepend_path "$NVM_BIN"
elif [ "$_air_env_nvm_version" = "default" ] && [ -r "$NVM_DIR/alias/default" ]; then
    IFS= read -r _air_env_nvm_version < "$NVM_DIR/alias/default" || true
fi
case "$_air_env_nvm_version" in
    ''|N/A|system|default|node|stable|unstable|lts/*|iojs*) ;;
    *)
        case "$_air_env_nvm_version" in
            v*) _air_env_nvm_bin="$NVM_DIR/versions/node/$_air_env_nvm_version/bin" ;;
            *) _air_env_nvm_bin="$NVM_DIR/versions/node/$_air_env_nvm_version/bin" ;;
        esac
        if [ ! -d "$_air_env_nvm_bin" ]; then
            for _air_env_nvm_candidate in "$NVM_DIR/versions/node/v$_air_env_nvm_version"*; do
                [ -d "$_air_env_nvm_candidate/bin" ] || continue
                _air_env_nvm_bin="$_air_env_nvm_candidate/bin"
                break
            done
        fi
        if [ -d "$_air_env_nvm_bin" ]; then
            export NVM_BIN="$_air_env_nvm_bin"
            _air_env_prepend_path "$NVM_BIN"
        fi
        ;;
esac
export PATH

_air_env_nvm_load() {
    unset -f nvm node npm npx 2>/dev/null || true
    [ -s "$NVM_DIR/nvm.sh" ] || return 127
    . "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
    command -v nvm >/dev/null 2>&1 && nvm use --silent default >/dev/null 2>&1 || true
}

nvm() {
    _air_env_nvm_load || return "$?"
    nvm "$@"
}

if ! command -v node >/dev/null 2>&1; then
    node() {
        _air_env_nvm_load || return "$?"
        node "$@"
    }
fi

if ! command -v npm >/dev/null 2>&1; then
    npm() {
        _air_env_nvm_load || return "$?"
        npm "$@"
    }
fi

if ! command -v npx >/dev/null 2>&1; then
    npx() {
        _air_env_nvm_load || return "$?"
        npx "$@"
    }
fi
unset _air_env_nvm_version _air_env_nvm_bin _air_env_nvm_candidate
    unset -f _air_env_prepend_path _air_env_expand_path_var
fi
