# Air native UI state.

ui_state_dir() {
    ui_state_home
}

ui_settings_path() {
    printf '%s\n' "$(ui_state_dir)/settings.sh"
}

ui_load_settings() {
    local settings

    [ "${AIR_UI_SETTINGS_LOADED:-0}" = "1" ] && return 0
    settings="$(ui_settings_path)"
    [ -r "$settings" ] && . "$settings"
    AIR_UI_MODE="${AIR_UI_MODE:-basic}"
    AIR_UI_HELPER_ENABLED="${AIR_UI_HELPER_ENABLED:-1}"
    AIR_UI_SETTINGS_LOADED=1
    export AIR_UI_MODE AIR_UI_HELPER_ENABLED AIR_UI_SETTINGS_LOADED
}

ui_helper_mode_enabled() {
    ui_load_settings
    [ "${AIR_UI_MODE:-basic}" = "helper" ]
}

ui_effective_mode() {
    if ui_is_plain; then
        printf 'plain\n'
    elif ui_helper_available; then
        printf 'helper\n'
    else
        printf 'basic\n'
    fi
}

ui_write_settings() {
    local mode="$1" dir settings tmp

    case "$mode" in
        basic|helper) ;;
        0) mode=basic ;;
        1) mode=helper ;;
        *) mode=basic ;;
    esac

    dir="$(ui_state_dir)"
    settings="$(ui_settings_path)"
    mkdir -p "$dir"
    tmp="$(mktemp)"
    {
        printf '# Generated by Air UI. Edit with air ui enable/disable.\n'
        printf 'AIR_UI_MODE=%s\n' "$(env_ui_quote "$mode")"
        printf 'AIR_UI_HELPER_ENABLED=1\n'
        printf 'AIR_UI_THEME=%s\n' "$(env_ui_quote "${AIR_UI_THEME:-default}")"
        printf 'AIR_UI_DENSITY=%s\n' "$(env_ui_quote "${AIR_UI_DENSITY:-normal}")"
    } > "$tmp"
    cp "$tmp" "$settings"
    chmod 0644 "$settings"
    rm -f "$tmp"
}

ui_enable_helper_state() {
    ui_write_settings helper
}

ui_disable_helper_state() {
    ui_write_settings basic
}

env_ui_quote() {
    local value="$1"

    value="${value//\'/\'\\\'\'}"
    printf "'%s'" "$value"
}

ui_load_settings
